# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Poetry and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export --dev -f requirements.txt >> requirements.txt
        pip install -r requirements.txt
    - name: Pytest
      run: |
        pytest -v # --cov=./parser/
    #- name: MyPy
      #run: |
        #mypy ./parser/
    #- name: flake8
      #run: |
         #stop the build if there are Python syntax errors or undefined names
        #flake8 ./parser/ --count --select=E9,F63,F7,F82 --show-source --statistics
         #exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 ./parser/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Bandit
      #run: |
        #bandit ./parser/
